### ISSUE TITLE
EUROSCOPE 3.2

### ISSUE THREAD

**Issue by raphaellprado** [sirluis/tmasalvador#5]
Verificar se os ALIAS .farol 
[alias_sbsv.txt](https://github.com/sirluis/tmasalvador/files/254263/alias_sbsv.txt)

OU

.faroldabarra
[alias_sbsv.txt](https://github.com/sirluis/tmasalvador/files/254264/alias_sbsv.txt)
 funcionam no 3.2

**Comment by sirluis** [comment]
A versão reduzida #4 permanecerá.

Att.
